services:
  app:
    build: .
    container_name: bank_app
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    container_name: bank_postgres
    environment:
      POSTGRES_USER: bank_user
      POSTGRES_PASSWORD: bank_password
      POSTGRES_DB: bank_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data:
