# Explicit DB connection for the Docker network
spring.datasource.url=jdbc:postgresql://postgres:5432/bank_db
spring.datasource.username=bank_user
spring.datasource.password=bank_password

# Turn off the compose extension inside the container
spring.docker.compose.enabled=false

spring.kafka.bootstrap-servers=kafka:29092